#@port = 5000
@port = 29701
@controller = johnamount
#@controller = johnamountsafe
#@controller = johnamountsafe2
#@controller = johnamountsafeasync
#@controller = johnamountsafewait

###

GET http://localhost:{{port}}/api/{{controller}}/allGood HTTP/1.1
content-type: application/json

{
}
###
GET http://localhost:{{port}}/api/{{controller}}/UnauthorisedSftp HTTP/1.1
content-type: application/json

{
}
###
GET http://localhost:{{port}}/api/{{controller}}/FileMissingOnSftp HTTP/1.1
content-type: application/json

{
}
###
GET http://localhost:{{port}}/api/{{controller}}/FileDoesntParse HTTP/1.1
content-type: application/json

{
}

