@port = 5000
@controller = johnamount
#@controller = johnamountsafe2
#@controller = johnamountsafeasync

###

GET http://localhost:{{port}}/api/{{controller}}/allGood HTTP/1.1
content-type: application/json

{
}
###
GET http://localhost:{{port}}/api/{{controller}}/UnauthorisedSftp HTTP/1.1
content-type: application/json

{
}
###
GET http://localhost:{{port}}/api/{{controller}}/FileMissingOnSftp HTTP/1.1
content-type: application/json

{
}
###
GET http://localhost:{{port}}/api/{{controller}}/FileDoesntParse HTTP/1.1
content-type: application/json

{
}

