@baseUrl = localhost:44333

@userId = 10000000-0000-0000-0000-000000000000
@tenantId = 20000000-0000-0000-0000-000000000000

GET https://{{baseUrl}}/tenant/{{tenantId}}/user/{{userId}} HTTP/1.1
content-type: application/json

{
}

###

GET https://{{baseUrl}}/tenant2/{{tenantId}}/user/{{userId}} HTTP/1.1
content-type: application/json

{
}

###
